### ISSUE TITLE
Great Plugin .... some notes

### ISSUE THREAD

**Issue by moafzalmulla** [robinzimmer1989/gatsby-wordpress-search#2]
Hi Rob,
Great search plugin for WP + gatsby
Probably worth mentioning in install that 2 things matter: 

- [x] You search which will show results must be called searchResults, or in my case I just added  a page called search.js to /pages in gatsby build

- [x] Whats also important is line 5 in the php file. If you're using v2 of WP Rest API. The endpoint will adjust from wp/v1 to wp/v2

Apart from that great plugin, happy to add those bits to notes or actual code via PR if you prefer.

Best
Mo
@tweetzal

**Comment by robinzimmer1989** [comment]
Hi Mo, thanks for your feedback!

I've updated the plugin code a little bit (hooks + maxResults prop) and pushed it to npm so it's easier to setup.

Regarding your first point: If you mean the Gatsby route in the gatsby-source-wordpress plugin then you're right, I've updated the readme file for clarification. But in general you can add the search component to any page since the results are fetched in a StaticQuery.

And I've updated the WP Rest API endpoint to version 2!

Let me know what you think!

Cheers
Robin

**Comment by moafzalmulla** [comment]
Thanks Rob
